name: Prebuild CI and Release

on:
  push:
    branches:
      - main
      - dev

  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install Dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Package Deb
        run: build-deb.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist